name: Issue Response

on:
  issues:
    types: [opened, edited]

jobs:
  auto_reply:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Response and Post Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const repo = context.repo.repo;
            const issueNumber = issue.number;
            const issueBody = issue.body;

            const systemPrompt = `Provide a helpful response based on the repository and issue description: ${issueBody}`;

            const groqApiKey = process.env.GROQ_API_KEY;

            const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${groqApiKey}`,
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                messages: [
                  { role: 'system', content: systemPrompt },
                  { role: 'user', content: issueBody },
                ],
                model: 'llama3-8b-8192',
              }),
            });

            if (!response.ok) {
              throw new Error('Failed to fetch response from LLM');
            }

            const data = await response.json();
            const llmResponse = data.choices[0].message.content;

            const initialCommentMessage = `${llmResponse}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: repo,
              issue_number: issueNumber,
              body: initialCommentMessage,
            });

            const followUpMessage = `
              If this issue persists or you need further assistance, please visit our support community at [discord.gg/iahispano](https://discord.gg/iahispano).
              Our community is available to help with any additional questions or concerns.
            `;

            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: repo,
              issue_number: issueNumber,
            });

            const hasFollowUpComment = comments.data.some(comment => 
              comment.body.includes('If this issue persists or you need further assistance')
            );

            if (!hasFollowUpComment) {
              setTimeout(async () => {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: repo,
                  issue_number: issueNumber,
                  body: followUpMessage,
                });
              }, 72 * 60 * 60 * 1000); // Delay in milliseconds (72 hours in this case)
            }
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
